spring:
  datasource:
    url: jdbc:mysql:///scfish?serverTimezone=UTC&charset=UTF-8&useSSL=false
    username: akigaze
    password: akigaze
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
  flyway:
    locations: classpath:db/migration
    enabled: true

