spring:
  datasource:
    url: jdbc:mysql:///scfish?serverTimezone=UTC&charset=UTF-8&useSSL=false
    # just change username and password in your local environment, don't commit it
    username: akigaze
    password: akigaze
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
  flyway:
    locations: classpath:db/migration
    enabled: true
scfish:
  mvc:
    exclude-path-patterns: /login,/register,/scfish/** # /scfish/** 也应该在登录后草能正常访问
