spring:
  datasource:
    url: jdbc:mysql:///scfish?serverTimezone=GMT%2B8&charset=UTF-8&useSSL=false
    # just change username and password in your local environment, don't commit it
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
  flyway:
    locations: classpath:db/migration
    enabled: true
logging:
  level:
    com.yogurt.scfish: DEBUG

scfish:
  mvc:
    exclude-path-patterns: /login,/register,/scfish/** # /scfish/** 也应该在登录后草能正常访问
